export { FavouritePage } from "./FavouritePage/FavouritePage"
export { LoginPage } from "./LoginPage/LoginPage"
export { MainPage } from "./MainPage/MainPage"
export { ProfilePage } from "./ProfilePage/ProfilePage"
export { RegistrationPage } from "./RegistrationPage/RegistrationPage"