export {Button} from "./UI/Button/Button"
export {Input} from "./UI/Input/Input"
export {Heading} from "./Typography/Heading/Heading"
export {AuthWith} from "./AuthWith/AuthWith.tsx"
export {Header} from "./UI/Header/Header.tsx"
export {SliderImg} from "./SliderImg/SliderImg.tsx"