export { FavouritePage } from "./Pages/FavouritePage"
export { LoginPage } from "./Pages/LoginPage"
export { MainPage } from "./Pages/MainPage"
export { ProfilePage } from "./Pages/ProfilePage"
export { RegistrationPage } from "./Pages/RegistrationPage"